version: '3.7'
services:
    rabbitmq:
        image: 'rabbitmq'
        ports:
          - 5672:5672
        restart: always
    redis-server:
        image: 'redis'
        ports:
          - 6379:6379
        restart: always
