version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0

    steps:
      - checkout
      - run:
          name: "Install global node modules"
          command: npm install
      - run:
          name: "Install workers node modules"
          command: cd ./workers/app/ ; npm install
      - run:
          name: "Run all tests in circle environment"
          command: npm run circleTest
      - run:
          name: "Run all tests and collect Coverage Reports"
          command: npm run circleCoverage
      - store_artifacts:
          path: ./workers/app/coverage
